version: '3.8'

services:
  # PHP-FPM Container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9001:9000"   # Đổi host port từ 9000 sang 9001
    depends_on:
      - db
    environment:
      # Thông tin cấu hình Laravel
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost
      # Kết nối DB
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: softui
      DB_USERNAME: root
      DB_PASSWORD: root
      APP_KEY: base64:pepMy3tk0+/Mr0RkeXJPs3e2n4OYGVHU0/lpXHgDM5I=
    networks:
      - laravel

  # MySQL Container
  db:
    image: mysql:8.0
    container_name: laravel_db2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: softui
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: root
    ports:
      - "33306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  # phpMyAdmin Container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "9090:80"    # Sử dụng cổng 9090 cho host
    depends_on:
      - db
    networks:
      - laravel

  # Nginx Container
  nginx:
    image: nginx:latest
    container_name: laravel_nginx2
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
